
import { Packages, Ethos, HandlerScript } from './types';

export const SECTORS: string[] = ['goa', 'himachal', 'rajasthan', 'kerala', 'uttarakhand', 'karnataka', 'meghalaya'];

export const HANDLER_AVATAR = 'https://ui-avatars.com/api/?name=HZ&background=000000&color=FFD700&size=128&bold=true';

export const HANDLER_CONFIG = {
  name: "HANDLER ZERO",
  role: "TACTICAL LEAD",
  version: "v10.1 [SYS_OP]"
};

export const GAME_CONFIG = {
    RANKS: {
        RECRUIT: 0,
        OPERATIVE: 1,
        GHOST: 2,
        LEGEND: 3
    }
};

export const HANDLER_SCRIPT: HandlerScript = {
  greeting: [
    "System Online. Welcome, Operative.",
    "Neural link established.",
    "Interface active."
  ],
  tutorial: [
    "Identity Verified. I am Handler Zero, your Tactical Lead.",
    "Navigation systems active. Use the Tactical Nav on the left to select a Sector.",
    "Your Goal: Unlock Level-5 Classified Assets hidden within the Mission Dossiers.",
    "I am tracking your cursor. Proceed when ready."
  ],
  sectorIntro: {
    goa: "Sector Goa loaded. Beach infiltration protocols active. View packages below.",
    himachal: "Sector Himachal loaded. High-altitude operations. Check thermal requirements.",
    rajasthan: "Sector Rajasthan loaded. Heritage sites identified. Luxury assets available.",
    kerala: "Sector Kerala loaded. Aquatic networks online. Houseboat availability: High.",
    uttarakhand: "Sector Uttarakhand loaded. Adventure sports protocols active.",
    karnataka: "Sector Karnataka loaded. Ruins and plantations mapped.",
    meghalaya: "Sector Meghalaya loaded. Meteorological scan complete. Prepare for rain."
  },
  idle: [
    "Operative, the tactical nav is on your left. Pick a sector.",
    "Stasis detected. Select a destination to view mission details.",
    "I have intel on 7 sectors. Awaiting your command.",
    "Do not waste bandwidth. Initiate a mission view."
  ],
  idleContext: {
    map: [
        "Global view active. Select a specific sector for detailed intel.",
        "Zooming is tactical, but booking is profitable. Choose a zone.",
        "Awaiting sector selection."
    ],
    sector: [
        "Multiple packages available. Click 'View Mission Dossier' for deep intel.",
        "Analyze the Value Index. These deals are time-sensitive.",
        "Select a mission to verify classified assets."
    ],
    ethos: [
        "Our operational philosophy is clear. Now apply it in the field.",
        "Understanding our code is good. Booking a mission is better.",
        "Return to the Map to deploy."
    ]
  },
  proactive: {
      goa: ["Advisory: Book early for peak season coastal assets.", "Intel: 'Budget Blitz' is our most popular extraction package.", "Tip: Use the Mission Dossier to check live weather."],
      himachal: ["Warning: High altitude requires acclimation. Check the 'Alpine Ascent' package.", "Tactical: Manali is crowded. Consider Tirthan Valley options.", "Intel: Parvati Valley packages include trekking gear."],
      rajasthan: ["Advisory: Desert camps fill up fast in winter.", "Intel: 'Royal Retreat' includes exclusive fort access.", "Tip: Verify intel to see hidden heritage inclusions."],
      kerala: ["Advisory: Houseboat inventory is low for next month.", "Intel: 'Varkala Vagabond' is optimized for solo operatives.", "Tip: Check the humidity levels in the Dossier before deploying."],
      meghalaya: ["Warning: Rain gear mandatory. See 'Mawsynram Monsoon' details.", "Intel: Living Root Bridges require physical endurance.", "Tip: Caving operations require a guide (included)."],
      uttarakhand: ["Advisory: Rafting season closes in monsoon. Book 'Ganges Rider' now.", "Intel: Auli Ski Resort is seasonal. Verify dates.", "Tip: Jim Corbett safari zones require permit pre-booking."],
      karnataka: ["Advisory: Coorg coffee estates offer best value in September.", "Intel: Hampi ruins are best explored at sunrise.", "Tip: Gokarna beaches offer stealthier alternatives to Goa."]
  },
  rageClick: [
      "Input overflow. Please select a mission calmly.",
      "Repeated clicking will not expedite the booking process.",
      "Calibrate your input device. Precision is key.",
      "Stop. Breathe. Select."
  ],
  highVelocity: [
      "Cursor velocity high. Scan the mission cards carefully.",
      "You're moving fast. Don't miss the tactical details.",
      "Slow down, Operative. The intel is detailed."
  ],
  scrolling: [
      "Scanning mission list...",
      "Multiple options available. Stop to view details.",
      "Scroll buffer active. Find your target package."
  ],
  hover: [
      "Target acquired. Click to view dossier.",
      "Potential mission identified.",
      "Accessing preliminary data...",
      "Good choice. Investigate further."
  ],
  restricted: [
    "This intel is Level-5 Classified. I need to verify your identity to unlock it.",
    "Restricted Asset. Establish a secure uplink (Name/Email) to view.",
    "Security Protocol Active. Verify your credentials to access this data.",
    "I can't release this data to anonymous users. Who are you?"
  ],
  success: [
    "Identity Verified. Decrypting assets now...",
    "Clearance Granted. Logistics unlocked.",
    "Uplink Secure. Showing classified data.",
    "Welcome to the inner circle, Operative."
  ],
  formPrompts: {
    askName: "Identify yourself. Enter your Operative Name.",
    askEmail: "Acknowledged. Enter secure Email frequency for dossier transmission.",
    processing: "Verifying credentials with HQ...",
    denied: "Error. Input invalid. Retry."
  }
};

export const PACKAGES: Packages = {
  goa: {
    title: "MISSION SECTOR: GOA",
    subtitle: "Tropical Reconnaissance Zone.",
    coords: [15.2993, 74.1240],
    missions: [
      { 
        codename: "Goa_Budget_Blitz", 
        price: "₹8,999", 
        threat: "Low", 
        vfm: "98%", 
        duration: "4D/3N", 
        brief: "Infiltrate North Goa. High-speed scooter maneuvers.", 
        tacticalBrief: "A rapid-deployment package for operatives on a tight budget. Focus is on mobility and social infiltration in the Anjuna-Vagator grid.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Goa/Goa_Budget_Blitz.png'}], 
        inclusions: ["Hostel Dorm (Anjuna)", "Scooter Fleet"], 
        lockedInclusions: ["Secret Rave Coordinates", "Thalassa Priority Code"],
        intelLevel: 1,
        optimalSeason: "NOV-FEB",
        weather: { temp: "32°C", condition: "Sunny", humidity: "75%" },
        transportMode: "Land",
        stayType: "Hostel"
      },
      { 
        codename: "Goa_Adrenaline_Rush", 
        price: "₹14,500", 
        threat: "High", 
        vfm: "92%", 
        duration: "4D/3N", 
        brief: "Aquatic dominance. Aerial and naval ops.", 
        tacticalBrief: "Amphibious operations capability required. Expect high G-forces during parasailing and rapid decompression during dive ops.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Goa/Goa_Adrenaline_Rush.png'}], 
        inclusions: ["Resort Base", "Parasailing Op"], 
        lockedInclusions: ["Hidden Cove Map", "GoPro Rental"],
        intelLevel: 3,
        optimalSeason: "OCT-MAR",
        weather: { temp: "29°C", condition: "Windy", humidity: "80%" },
        transportMode: "Water",
        stayType: "Resort"
      },
      { 
        codename: "Goa_Southern_Serenity", 
        price: "₹17,999", 
        threat: "Low", 
        vfm: "92%", 
        duration: "5D/4N", 
        brief: "Silence protocols active. Yoga calibration.", 
        tacticalBrief: "Deep cover operation in Palolem. Low noise signature essential. Biological recalibration via yoga included.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Goa/Goa_Southern_Serenity.png'}], 
        inclusions: ["Boutique Hideout", "Yoga"], 
        lockedInclusions: ["Private Sunset Point", "Chef's Table"],
        intelLevel: 2,
        optimalSeason: "DEC-APR",
        weather: { temp: "30°C", condition: "Calm", humidity: "65%" },
        transportMode: "Land",
        stayType: "Villa"
      },
      { 
        codename: "Goa_Old_Goa_Ops", 
        price: "₹10,500", 
        threat: "Low", 
        vfm: "95%", 
        duration: "3D/2N", 
        brief: "Heritage decryption. Colonial architecture survey.", 
        tacticalBrief: "Historical data mining. Operatives will scan 16th-century Portuguese infrastructure. E-Bike mobility provided.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Goa/Goa_Old_Goa_Ops.png'}], 
        inclusions: ["Heritage Villa", "E-Bike Tour"], 
        lockedInclusions: ["Crypt Access", "Feni Tasting Lab"],
        intelLevel: 4,
        optimalSeason: "JUN-SEP",
        weather: { temp: "27°C", condition: "Overcast", humidity: "90%" },
        transportMode: "Land",
        stayType: "Villa"
      },
      { 
        codename: "Goa_Jungle_Jam", 
        price: "₹12,000", 
        threat: "Medium", 
        vfm: "90%", 
        duration: "4D/3N", 
        brief: "Hinterland extraction. Waterfall navigation.", 
        tacticalBrief: "Off-grid survival scenario. Mollem National Park traversal. Leech protection recommended.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Goa/Goa_Jungle_Jam.png'}], 
        inclusions: ["Eco-Lodge", "Spice Plantation"], 
        lockedInclusions: ["Dudhsagar Jeep Pass", "Night Trek Map"],
        intelLevel: 3,
        optimalSeason: "AUG-NOV",
        weather: { temp: "24°C", condition: "Rain", humidity: "95%" },
        transportMode: "Land",
        stayType: "Camp"
      },
      { 
        codename: "Goa_Casino_Royale", 
        price: "₹25,000", 
        threat: "Low", 
        vfm: "85%", 
        duration: "3D/2N", 
        brief: "High roller infiltration. Mandovi river ops.", 
        tacticalBrief: "Social engineering focus. Tuxedo/Gown camouflage required. Asset liquidation risk: High.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Goa/Goa_Casino_Royale.png'}], 
        inclusions: ["5-Star Hotel", "Casino Chips"], 
        lockedInclusions: ["VIP Lounge Access", "Private Yacht Hour"],
        intelLevel: 5,
        optimalSeason: "YEAR-ROUND",
        weather: { temp: "26°C", condition: "Clear", humidity: "80%" },
        transportMode: "Water",
        stayType: "Hotel"
      },
      { 
        codename: "Goa_Island_Hop", 
        price: "₹9,500", 
        threat: "Medium", 
        vfm: "96%", 
        duration: "4D/3N", 
        brief: "Divar & Chorao surveillance. Ferry logistics.", 
        tacticalBrief: "Naval transport dependent. Time-table synchronization critical. Bird watching optics advised.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Goa/Goa_Island_Hop.png'}], 
        inclusions: ["Homestay", "Ferry Pass"], 
        lockedInclusions: ["Bird Sanctuary Guide", "Local Tavern List"],
        intelLevel: 2,
        optimalSeason: "DEC-FEB",
        weather: { temp: "29°C", condition: "Breezy", humidity: "70%" },
        transportMode: "Water",
        stayType: "Homestay"
      }
    ]
  },
  himachal: {
    title: "SECTOR: HIMACHAL",
    subtitle: "Alpine Elevation Ops.",
    coords: [32.0836, 77.1711],
    missions: [
      { 
        codename: "Himachal_Alpine_Ascent", 
        price: "₹12,999", 
        threat: "Medium", 
        vfm: "95%", 
        duration: "6D/5N", 
        brief: "Target: Manali. Acclimatization required.", 
        tacticalBrief: "Standard alpine deployment. Solang Valley incursions expected. Snow chain protocols in effect.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Himachal/Himachal_Alpine_Ascent.png'}], 
        inclusions: ["Base Camp (Manali)", "Solang Sortie"], 
        lockedInclusions: ["Thermal Springs", "4x4 Guide"],
        intelLevel: 2,
        optimalSeason: "MAY-JUN",
        weather: { temp: "15°C", condition: "Cool", humidity: "40%" },
        transportMode: "Land",
        stayType: "Hotel"
      },
      { 
        codename: "Himachal_Parvati_Pilgrim", 
        price: "₹9,999", 
        threat: "High", 
        vfm: "96%", 
        duration: "5D/4N", 
        brief: "Target: Kasol. Psychedelic terrain mapping.", 
        tacticalBrief: "Valley is known for psycho-active interference. Maintain distinct reality check. Trekking stamina required.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Himachal/Himachal_Parvati_Pilgrim.png'}], 
        inclusions: ["River Camp", "Kheerganga Trek"], 
        lockedInclusions: ["Full Moon Coordinates", "Hidden Cafe"],
        intelLevel: 3,
        optimalSeason: "APR-JUN",
        weather: { temp: "12°C", condition: "Clear", humidity: "50%" },
        transportMode: "Trek",
        stayType: "Camp"
      },
      { 
        codename: "Himachal_Spiti_Circuit", 
        price: "₹18,500", 
        threat: "Extreme", 
        vfm: "91%", 
        duration: "8D/7N", 
        brief: "High altitude desert traversal. Oxygen check.", 
        tacticalBrief: "Extreme environment. Roads are theoretical. AMS (Acute Mountain Sickness) mitigation drugs mandatory.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Himachal/Himachal_Spiti_Circuit.png'}], 
        inclusions: ["Homestays", "Tempo Traveller"], 
        lockedInclusions: ["Monastery Key", "Fossil Park Map"],
        intelLevel: 5,
        optimalSeason: "JUN-SEP",
        weather: { temp: "5°C", condition: "Arid", humidity: "20%" },
        transportMode: "Land",
        stayType: "Homestay"
      },
      { 
        codename: "Himachal_Dharamshala_Zen", 
        price: "₹11,000", 
        threat: "Low", 
        vfm: "94%", 
        duration: "5D/4N", 
        brief: "Exile protocols. Monastery infiltration.", 
        tacticalBrief: "Cultural immersion. Silence is a weapon here. Momos are the primary fuel source.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Himachal/Himachal_Dharamshala_Zen.png'}], 
        inclusions: ["Guesthouse", "Meditation Pass"], 
        lockedInclusions: ["Lama Debate Schedule", "Best Momo Stall"],
        intelLevel: 2,
        optimalSeason: "MAR-JUN",
        weather: { temp: "18°C", condition: "Rain", humidity: "70%" },
        transportMode: "Land",
        stayType: "Hotel"
      },
      { 
        codename: "Himachal_Bir_Flyboy", 
        price: "₹14,500", 
        threat: "High", 
        vfm: "90%", 
        duration: "4D/3N", 
        brief: "Aerial reconnaissance. Paragliding mandatory.", 
        tacticalBrief: "Vertical drop simulation. Thermal updraft navigation. Do not eat heavy before deployment.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Himachal/Himachal_Bir_Flyboy.png'}], 
        inclusions: ["Landing Site Stay", "Paragliding"], 
        lockedInclusions: ["GoPro Footage", "Sunset Cafe Spot"],
        intelLevel: 4,
        optimalSeason: "OCT-NOV",
        weather: { temp: "20°C", condition: "Sunny", humidity: "45%" },
        transportMode: "Air",
        stayType: "Hotel"
      },
      { 
        codename: "Himachal_Shimla_Colonial", 
        price: "₹13,500", 
        threat: "Low", 
        vfm: "88%", 
        duration: "4D/3N", 
        brief: "Capital city survey. Gauge preservation.", 
        tacticalBrief: "Navigating the Mall Road requires crowd-weaving dexterity. Heritage train is slow but strategic.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Himachal/Himachal_Shimla_Colonial.png'}], 
        inclusions: ["Heritage Hotel", "Toy Train"], 
        lockedInclusions: ["Viceregal Lodge Pass", "Secret Bakery"],
        intelLevel: 1,
        optimalSeason: "DEC-JAN",
        weather: { temp: "8°C", condition: "Fog", humidity: "60%" },
        transportMode: "Land",
        stayType: "Hotel"
      },
      { 
        codename: "Himachal_Tirthan_Stealth", 
        price: "₹10,500", 
        threat: "Medium", 
        vfm: "97%", 
        duration: "4D/3N", 
        brief: "Trout fishing operations. Valley silence.", 
        tacticalBrief: "GHNP (Great Himalayan National Park) buffer zone. Bio-diversity hot spot. Stealth camping protocols.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Himachal/Himachal_Tirthan_Stealth.png'}], 
        inclusions: ["Riverside Cottage", "Angling Permit"], 
        lockedInclusions: ["Hidden Waterfall", "Local Guide"],
        intelLevel: 4,
        optimalSeason: "MAR-MAY",
        weather: { temp: "14°C", condition: "Breezy", humidity: "55%" },
        transportMode: "Land",
        stayType: "Camp"
      }
    ]
  },
  rajasthan: { 
    title: "SECTOR: RAJASTHAN", 
    subtitle: "Arid Heritage Fortification.", 
    coords: [27.0238, 74.2179], 
    missions: [
      { 
        codename: "Rajasthan_Royal_Retreat", 
        price: "₹15,999", 
        threat: "Low", 
        vfm: "90%", 
        duration: "5D/4N", 
        brief: "Citadel infiltration. Heritage protocols.", 
        tacticalBrief: "Jaipur-Jodhpur axis. Fortification analysis. Expect royal treatment (literally).",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Rajasthan/Rajasthan_Royal_Retreat.png'}], 
        inclusions: ["Haveli Stay", "Fort Pass"], 
        lockedInclusions: ["Private Stepwell", "Tea Ceremony"],
        intelLevel: 2,
        optimalSeason: "OCT-MAR",
        weather: { temp: "32°C", condition: "Sunny", humidity: "20%" },
        transportMode: "Land",
        stayType: "Hotel"
      },
      { 
        codename: "Rajasthan_Desert_Dreamer", 
        price: "₹11,999", 
        threat: "Medium", 
        vfm: "94%", 
        duration: "4D/3N", 
        brief: "Dune navigation and astronomical survey.", 
        tacticalBrief: "Sam Sand Dunes deployment. Camel cavalry unit assigned. Night ops involve deep space telemetry (stargazing).",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Rajasthan/Rajasthan_Desert_Dreamer.png'}], 
        inclusions: ["Desert Camp", "Camel Unit"], 
        lockedInclusions: ["Dune Bashing", "Stargazing"],
        intelLevel: 3,
        optimalSeason: "NOV-FEB",
        weather: { temp: "35°C", condition: "Dry", humidity: "10%" },
        transportMode: "Land",
        stayType: "Camp"
      },
      { 
        codename: "Rajasthan_Blue_Scout", 
        price: "₹10,500", 
        threat: "Low", 
        vfm: "95%", 
        duration: "3D/2N", 
        brief: "Jodhpur maze navigation. Zipline extraction.", 
        tacticalBrief: "Blue City labyrinth. Navigation systems unreliable. Visual markers essential. Zipline extraction from Mehrangarh.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Rajasthan/Rajasthan_Blue_Scout.png'}], 
        inclusions: ["Old City Stay", "Mehrangarh Entry"], 
        lockedInclusions: ["Flying Fox Zipline", "Best Lassi Intel"],
        intelLevel: 3,
        optimalSeason: "OCT-MAR",
        weather: { temp: "33°C", condition: "Sunny", humidity: "15%" },
        transportMode: "Land",
        stayType: "Homestay"
      },
      { 
        codename: "Rajasthan_Lake_Luxe", 
        price: "₹19,000", 
        threat: "Low", 
        vfm: "89%", 
        duration: "4D/3N", 
        brief: "Udaipur aquatic luxury surveillance.", 
        tacticalBrief: "James Bond protocol (Octopussy filming location). High-end surveillance. Dinner jacket recommended.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Rajasthan/Rajasthan_Lake_Luxe.png'}], 
        inclusions: ["Lake View Room", "Boat Ride"], 
        lockedInclusions: ["Jag Mandir Dinner", "Art Collection"],
        intelLevel: 4,
        optimalSeason: "SEP-MAR",
        weather: { temp: "30°C", condition: "Clear", humidity: "30%" },
        transportMode: "Water",
        stayType: "Hotel"
      },
      { 
        codename: "Rajasthan_Haunted_Ruins", 
        price: "₹8,500", 
        threat: "High", 
        vfm: "92%", 
        duration: "2D/1N", 
        brief: "Bhangarh paranormal investigation.", 
        tacticalBrief: "Psychic shielding required. Do not remain in zone post-sunset. Legal restriction active.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Rajasthan/Rajasthan_Haunted_Ruins.png'}], 
        inclusions: ["Alwar Hotel", "Night Permit"], 
        lockedInclusions: ["Ghost Hunter Kit", "Local Legend Guide"],
        intelLevel: 5,
        optimalSeason: "WINTER",
        weather: { temp: "25°C", condition: "Eerie", humidity: "25%" },
        transportMode: "Land",
        stayType: "Hotel"
      },
      { 
        codename: "Rajasthan_Tiger_Trail", 
        price: "₹16,500", 
        threat: "Medium", 
        vfm: "91%", 
        duration: "3D/2N", 
        brief: "Ranthambore predator tracking.", 
        tacticalBrief: "Apex predator territory. Camouflage essential. Telephoto lens required for safe acquisition.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Rajasthan/Rajasthan_Tiger_Trail.png'}], 
        inclusions: ["Jungle Resort", "Canter Safari"], 
        lockedInclusions: ["Zone 1 Access", "Private Naturalist"],
        intelLevel: 4,
        optimalSeason: "APR-JUN",
        weather: { temp: "38°C", condition: "Hot", humidity: "15%" },
        transportMode: "Land",
        stayType: "Resort"
      },
      { 
        codename: "Rajasthan_Fresco_Find", 
        price: "₹9,999", 
        threat: "Low", 
        vfm: "96%", 
        duration: "3D/2N", 
        brief: "Shekhawati open art gallery scan.", 
        tacticalBrief: "Visual data overload. Painted Havelis contain historical encryption. Walk-heavy mission.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Rajasthan/Rajasthan_Fresco_Find.png'}], 
        inclusions: ["Mandawa Haveli", "Walking Tour"], 
        lockedInclusions: ["Restoration Workshop", "Antique Deal"],
        intelLevel: 2,
        optimalSeason: "NOV-FEB",
        weather: { temp: "22°C", condition: "Sunny", humidity: "20%" },
        transportMode: "Land",
        stayType: "Homestay"
      }
    ]
  },
  kerala: { 
    title: "SECTOR: KERALA", 
    subtitle: "Aquatic Labyrinth Network.", 
    coords: [10.8505, 76.2711], 
    missions: [
      { 
        codename: "Kerala_Backwater_Bliss", 
        price: "₹13,999", 
        threat: "Low", 
        vfm: "94%", 
        duration: "4D/3N", 
        brief: "Houseboat command center.", 
        tacticalBrief: "Mobile HQ established on Vembanad Lake. Communications jamming likely due to serenity. Fresh catch protocol active.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Kerala/Kerala_Backwater_Bliss.png'}], 
        inclusions: ["Private Vessel", "Mess Hall"], 
        lockedInclusions: ["Toddy Shop Map", "Canoe Upgrade"],
        intelLevel: 2,
        optimalSeason: "AUG-MAR",
        weather: { temp: "29°C", condition: "Humid", humidity: "85%" },
        transportMode: "Water",
        stayType: "Houseboat"
      },
      { 
        codename: "Kerala_Varkala_Vagabond", 
        price: "₹9,999", 
        threat: "Low", 
        vfm: "95%", 
        duration: "5D/4N", 
        brief: "Cliffside surveillance.", 
        tacticalBrief: "Geological anomaly: Cliffs adjacent to Arabian Sea. High hippie concentration. Surf conditions variable.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Kerala/Kerala_Varkala_Vagabond.png'}], 
        inclusions: ["Cliff Guesthouse", "Surf Lesson"], 
        lockedInclusions: ["Secret Beach", "Electro Event"],
        intelLevel: 3,
        optimalSeason: "DEC-MAR",
        weather: { temp: "31°C", condition: "Sunny", humidity: "75%" },
        transportMode: "Land",
        stayType: "Hostel"
      },
      { 
        codename: "Kerala_Munnar_Mist", 
        price: "₹11,500", 
        threat: "Medium", 
        vfm: "93%", 
        duration: "3D/2N", 
        brief: "High altitude plantation recon.", 
        tacticalBrief: "Visibility low due to mist. Tea caffeine levels high. Endemic species (Nilgiri Tahr) scan required.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Kerala/Kerala_Munnar_Mist.png'}], 
        inclusions: ["Tea Estate Stay", "Jeep Safari"], 
        lockedInclusions: ["Tea Tasting Session", "Kolukkumalai Sunrise"],
        intelLevel: 2,
        optimalSeason: "SEP-MAR",
        weather: { temp: "18°C", condition: "Fog", humidity: "90%" },
        transportMode: "Land",
        stayType: "Resort"
      },
      { 
        codename: "Kerala_Wayanad_Wild", 
        price: "₹12,500", 
        threat: "Medium", 
        vfm: "92%", 
        duration: "4D/3N", 
        brief: "Forest cave infiltration.", 
        tacticalBrief: "Neolithic glyphs detected in Edakkal. Dense canopy cover. Elephant corridor caution.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Kerala/Kerala_Wayanad_Wild.png'}], 
        inclusions: ["Treehouse", "Edakkal Caves"], 
        lockedInclusions: ["Night Safari", "Bamboo Rafting"],
        intelLevel: 3,
        optimalSeason: "OCT-MAY",
        weather: { temp: "22°C", condition: "Overcast", humidity: "80%" },
        transportMode: "Trek",
        stayType: "Resort"
      },
      { 
        codename: "Kerala_Kochi_Colonial", 
        price: "₹10,000", 
        threat: "Low", 
        vfm: "96%", 
        duration: "3D/2N", 
        brief: "Fort Kochi heritage scan.", 
        tacticalBrief: "Multi-colonial layering (Dutch, Portuguese, British). Chinese Fishing Net operation analysis.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Kerala/Kerala_Kochi_Colonial.png'}], 
        inclusions: ["Boutique Hotel", "Biennale Pass"], 
        lockedInclusions: ["Kathakali Backstage", "Art Cafe List"],
        intelLevel: 4,
        optimalSeason: "DEC-FEB",
        weather: { temp: "30°C", condition: "Rain", humidity: "85%" },
        transportMode: "Land",
        stayType: "Hotel"
      },
      { 
        codename: "Kerala_Thekkady_Tiger", 
        price: "₹14,000", 
        threat: "High", 
        vfm: "91%", 
        duration: "3D/2N", 
        brief: "Periyar reserve navigation.", 
        tacticalBrief: "Aquatic safari insertion into Tiger Reserve. Silent propulsion required. Spice scent heavy.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Kerala/Kerala_Thekkady_Tiger.png'}], 
        inclusions: ["Jungle Inn", "Boat Safari"], 
        lockedInclusions: ["Border Hiking", "Spice Farm"],
        intelLevel: 3,
        optimalSeason: "OCT-FEB",
        weather: { temp: "25°C", condition: "Cloudy", humidity: "70%" },
        transportMode: "Water",
        stayType: "Camp"
      },
      { 
        codename: "Kerala_Kovalam_Coast", 
        price: "₹16,000", 
        threat: "Low", 
        vfm: "90%", 
        duration: "4D/3N", 
        brief: "Lighthouse beach operations.", 
        tacticalBrief: "Classic beach deployment. UV exposure high. Oil massage recuperation protocols available.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Kerala/Kerala_Kovalam_Coast.png'}], 
        inclusions: ["Beach Resort", "Ayurveda"], 
        lockedInclusions: ["Private Cove", "Seafood Feast"],
        intelLevel: 1,
        optimalSeason: "SEP-MAR",
        weather: { temp: "32°C", condition: "Sunny", humidity: "80%" },
        transportMode: "Land",
        stayType: "Resort"
      }
    ]
  },
  meghalaya: { 
    title: "SECTOR: MEGHALAYA", 
    subtitle: "Cloud Base Atmos.", 
    coords: [25.4670, 91.3662], 
    missions: [
      { 
        codename: "ME_Mawsynram_Monsoon", 
        price: "₹16,500", 
        threat: "Extreme", 
        vfm: "95%", 
        duration: "5D/4N", 
        brief: "Max precipitation zone.", 
        tacticalBrief: "Wettest place on Earth. Hydro-gear stress test. Living root infrastructure analysis.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Meghalaya/ME_Mawsynram_Monsoon.png'}], 
        inclusions: ["Cloud Stay", "Root Bridges"], 
        lockedInclusions: ["Sacred Forest", "Khasi Feast"],
        intelLevel: 5,
        optimalSeason: "JUN-SEP",
        weather: { temp: "18°C", condition: "Downpour", humidity: "99%" },
        transportMode: "Land",
        stayType: "Resort"
      },
      { 
        codename: "ME_Root_Scout", 
        price: "₹12,000", 
        threat: "High", 
        vfm: "94%", 
        duration: "4D/3N", 
        brief: "Nongriat biological bridge traversal.", 
        tacticalBrief: "3000 step descent. Quadricep failure imminent. Bio-engineering marvels (Double Decker bridge) target.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Meghalaya/ME_Root_Scout.png'}], 
        inclusions: ["Homestay", "Double Decker Trek"], 
        lockedInclusions: ["Rainbow Falls", "Natural Pool"],
        intelLevel: 4,
        optimalSeason: "OCT-APR",
        weather: { temp: "22°C", condition: "Humid", humidity: "85%" },
        transportMode: "Trek",
        stayType: "Homestay"
      },
      { 
        codename: "ME_Dawki_Run", 
        price: "₹11,500", 
        threat: "Low", 
        vfm: "96%", 
        duration: "3D/2N", 
        brief: "Transparent water navigation.", 
        tacticalBrief: "Umngot River. Water clarity 100%. Boat appears to levitate. Border proximity to Bangladesh: Close.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Meghalaya/ME_Dawki_Run.png'}], 
        inclusions: ["Riverside Camp", "Boating"], 
        lockedInclusions: ["Border View", "Cliff Jumping"],
        intelLevel: 2,
        optimalSeason: "NOV-APR",
        weather: { temp: "24°C", condition: "Clear", humidity: "60%" },
        transportMode: "Water",
        stayType: "Camp"
      },
      { 
        codename: "ME_Shillong_Rock", 
        price: "₹10,000", 
        threat: "Low", 
        vfm: "97%", 
        duration: "3D/2N", 
        brief: "Urban culture and acoustic survey.", 
        tacticalBrief: "Rock capital of India. Acoustic intel gathering. Traffic density high. Cafe culture scan.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Meghalaya/ME_Shillong_Rock.png'}], 
        inclusions: ["City Hotel", "Cafe Crawl"], 
        lockedInclusions: ["Dylan's Cafe", "Live Gig Entry"],
        intelLevel: 3,
        optimalSeason: "YEAR-ROUND",
        weather: { temp: "19°C", condition: "Cool", humidity: "50%" },
        transportMode: "Land",
        stayType: "Hotel"
      },
      { 
        codename: "ME_Cave_Ops", 
        price: "₹14,000", 
        threat: "Extreme", 
        vfm: "92%", 
        duration: "4D/3N", 
        brief: "Subterranean mapping. Krem Liat Prah.", 
        tacticalBrief: "Claustrophobia warning. Headlamps mandatory. Fossil extraction (simulated) only.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Meghalaya/ME_Cave_Ops.png'}], 
        inclusions: ["Caving Gear", "Guide"], 
        lockedInclusions: ["Unmapped Chamber", "Fossil Find"],
        intelLevel: 5,
        optimalSeason: "NOV-MAR",
        weather: { temp: "15°C", condition: "Dark", humidity: "90%" },
        transportMode: "Trek",
        stayType: "Camp"
      },
      { 
        codename: "ME_Waterfall_Rappel", 
        price: "₹13,500", 
        threat: "High", 
        vfm: "93%", 
        duration: "3D/2N", 
        brief: "Vertical descent operations.", 
        tacticalBrief: "Nohkalikai Falls vicinity. Harness integrity check critical. Drone footage opportunity.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Meghalaya/ME_Waterfall_Rappel.png'}], 
        inclusions: ["Adventure Camp", "Rappelling"], 
        lockedInclusions: ["Secret Canyon", "Drone Shot"],
        intelLevel: 4,
        optimalSeason: "OCT-MAY",
        weather: { temp: "21°C", condition: "Mist", humidity: "80%" },
        transportMode: "Land",
        stayType: "Camp"
      },
      { 
        codename: "ME_Sacred_Spirit", 
        price: "₹11,000", 
        threat: "Low", 
        vfm: "95%", 
        duration: "3D/2N", 
        brief: "Mawphlang spiritual recon.", 
        tacticalBrief: "Sacred Grove rules: Take nothing, leave nothing. Ancient monoliths detected.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Meghalaya/ME_Sacred_Spirit.png'}], 
        inclusions: ["Heritage Hut", "Grove Walk"], 
        lockedInclusions: ["Shaman Meet", "Local Brew"],
        intelLevel: 2,
        optimalSeason: "YEAR-ROUND",
        weather: { temp: "18°C", condition: "Cloudy", humidity: "65%" },
        transportMode: "Trek",
        stayType: "Homestay"
      }
    ]
  },
  uttarakhand: { 
    title: "SECTOR: UTTARAKHAND", 
    subtitle: "Divine Peak Sanctum.", 
    coords: [30.0668, 79.0193], 
    missions: [
      { 
        codename: "UK_Ganges_Rider", 
        price: "₹9,500", 
        threat: "Medium", 
        vfm: "96%", 
        duration: "3D/2N", 
        brief: "Rapid extraction protocols.", 
        tacticalBrief: "Grade III/IV rapids. Rishikesh sector. Involuntary hydration probable.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Uttarakhand/UK_Ganges_Rider.png'}], 
        inclusions: ["River Camp", "Rafting 16km"], 
        lockedInclusions: ["Beatles Ashram", "Secret Falls"],
        intelLevel: 2,
        optimalSeason: "SEP-JUN",
        weather: { temp: "28°C", condition: "Sunny", humidity: "40%" },
        transportMode: "Water",
        stayType: "Camp"
      },
      { 
        codename: "UK_Nainital_Nautical", 
        price: "₹11,000", 
        threat: "Low", 
        vfm: "94%", 
        duration: "3D/2N", 
        brief: "Lake district surveillance.", 
        tacticalBrief: "Eye-shaped lake. High tourist density on Mall Road. Elevation retreat.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Uttarakhand/UK_Nainital_Nautical.png'}], 
        inclusions: ["Lake Hotel", "Yachting"], 
        lockedInclusions: ["Tiffin Top Hike", "Candle Dinner"],
        intelLevel: 1,
        optimalSeason: "YEAR-ROUND",
        weather: { temp: "20°C", condition: "Pleasant", humidity: "50%" },
        transportMode: "Water",
        stayType: "Hotel"
      },
      { 
        codename: "UK_Corbett_Camo", 
        price: "₹15,500", 
        threat: "High", 
        vfm: "91%", 
        duration: "4D/3N", 
        brief: "Jim Corbett tactical stealth.", 
        tacticalBrief: "Project Tiger zone. Open-top jeep vulnerability. Binoculars required.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Uttarakhand/UK_Corbett_Camo.png'}], 
        inclusions: ["Forest Lodge", "Jeep Safari"], 
        lockedInclusions: ["Dhikala Zone", "Elephant Path"],
        intelLevel: 3,
        optimalSeason: "NOV-JUN",
        weather: { temp: "25°C", condition: "Dry", humidity: "30%" },
        transportMode: "Land",
        stayType: "Resort"
      },
      { 
        codename: "UK_Valley_Flowers", 
        price: "₹13,000", 
        threat: "Medium", 
        vfm: "95%", 
        duration: "6D/5N", 
        brief: "Bio-survey in high altitude.", 
        tacticalBrief: "UNESCO World Heritage Site. Floral blooming phase critical. High endurance trek.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Uttarakhand/UK_Valley_Flowers.png'}], 
        inclusions: ["Ghangaria Camp", "Trek Permit"], 
        lockedInclusions: ["Hemkund Sahib", "Rare Flora Map"],
        intelLevel: 4,
        optimalSeason: "JUL-SEP",
        weather: { temp: "15°C", condition: "Drizzle", humidity: "70%" },
        transportMode: "Trek",
        stayType: "Camp"
      },
      { 
        codename: "UK_Mussoorie_Mist", 
        price: "₹12,000", 
        threat: "Low", 
        vfm: "92%", 
        duration: "4D/3N", 
        brief: "Queen of Hills observation.", 
        tacticalBrief: "Colonial nostalgia. Ruskin Bond sighting probability: Low but non-zero.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Uttarakhand/UK_Mussoorie_Mist.png'}], 
        inclusions: ["Colonial Hotel", "Mall Road"], 
        lockedInclusions: ["Landour Bakehouse", "George Everest"],
        intelLevel: 2,
        optimalSeason: "YEAR-ROUND",
        weather: { temp: "18°C", condition: "Mist", humidity: "80%" },
        transportMode: "Land",
        stayType: "Hotel"
      },
      { 
        codename: "UK_Auli_Alpine", 
        price: "₹16,000", 
        threat: "Medium", 
        vfm: "90%", 
        duration: "4D/3N", 
        brief: "Snow terrain maneuvers.", 
        tacticalBrief: "Skiing infrastructure active. Cable car extraction point. Nanda Devi visual confirmation.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Uttarakhand/UK_Auli_Alpine.png'}], 
        inclusions: ["Ski Resort", "Lesson"], 
        lockedInclusions: ["Gorson Bugyal", "Cable Car VIP"],
        intelLevel: 3,
        optimalSeason: "JAN-MAR",
        weather: { temp: "-2°C", condition: "Snow", humidity: "40%" },
        transportMode: "Land",
        stayType: "Resort"
      },
      { 
        codename: "UK_Chopta_Trek", 
        price: "₹10,500", 
        threat: "Medium", 
        vfm: "97%", 
        duration: "3D/2N", 
        brief: "Tungnath summit push.", 
        tacticalBrief: "Highest Shiva temple. Mini-Switzerland terrain. Snow trek probable in winter.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Uttarakhand/UK_Chopta_Trek.png'}], 
        inclusions: ["Camping", "Guide"], 
        lockedInclusions: ["Chandrashila Peak", "Snow Gear"],
        intelLevel: 3,
        optimalSeason: "YEAR-ROUND",
        weather: { temp: "10°C", condition: "Clear", humidity: "30%" },
        transportMode: "Trek",
        stayType: "Camp"
      }
    ]
  },
  karnataka: { 
    title: "SECTOR: KARNATAKA", 
    subtitle: "Ancient Ruin Grid.", 
    coords: [15.3173, 75.7139], 
    missions: [
      { 
        codename: "KA_Hampi_Historian", 
        price: "₹10,999", 
        threat: "Low", 
        vfm: "97%", 
        duration: "4D/3N", 
        brief: "Lost empire decryption.", 
        tacticalBrief: "Boulder terrain. Vijayanagara ruins scattered. Coracle stability questionable but fun.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Karnataka/KA_Hampi_Historian.png'}], 
        inclusions: ["Boulder Stay", "Rickshaw Sortie"], 
        lockedInclusions: ["Jam Session", "Cave Art"],
        intelLevel: 2,
        optimalSeason: "OCT-MAR",
        weather: { temp: "34°C", condition: "Sunny", humidity: "30%" },
        transportMode: "Land",
        stayType: "Homestay"
      },
      { 
        codename: "KA_Coorg_Coffee", 
        price: "₹12,500", 
        threat: "Low", 
        vfm: "94%", 
        duration: "3D/2N", 
        brief: "Plantation camouflage ops.", 
        tacticalBrief: "Kodagu district. Caffeine saturation high. Pork curry consumption authorized.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Karnataka/KA_Coorg_Coffee.png'}], 
        inclusions: ["Estate Stay", "Coffee Tour"], 
        lockedInclusions: ["Private Stream", "Pandi Curry"],
        intelLevel: 2,
        optimalSeason: "SEP-MAR",
        weather: { temp: "22°C", condition: "Breezy", humidity: "60%" },
        transportMode: "Land",
        stayType: "Resort"
      },
      { 
        codename: "KA_Gokarna_Bum", 
        price: "₹9,500", 
        threat: "Medium", 
        vfm: "96%", 
        duration: "4D/3N", 
        brief: "Coastal trek and beach bivouac.", 
        tacticalBrief: "Alternative to Goa. Trekking between beaches (Om, Kudle, Paradise) mandatory.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Karnataka/KA_Gokarna_Bum.png'}], 
        inclusions: ["Beach Shack", "Trek Guide"], 
        lockedInclusions: ["Bioluminescence", "Secret Cove"],
        intelLevel: 3,
        optimalSeason: "OCT-MAR",
        weather: { temp: "30°C", condition: "Sunny", humidity: "70%" },
        transportMode: "Trek",
        stayType: "Camp"
      },
      { 
        codename: "KA_Chikmagalur_Peak", 
        price: "₹11,000", 
        threat: "Medium", 
        vfm: "95%", 
        duration: "3D/2N", 
        brief: "Mullayanagiri summit assault.", 
        tacticalBrief: "Highest peak in Karnataka. Windy conditions. Coffee estate proximity high.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Karnataka/KA_Chikmagalur_Peak.png'}], 
        inclusions: ["Hill Resort", "Jeep Hire"], 
        lockedInclusions: ["Baba Budangiri", "Hidden Lake"],
        intelLevel: 2,
        optimalSeason: "SEP-MAR",
        weather: { temp: "19°C", condition: "Mist", humidity: "75%" },
        transportMode: "Land",
        stayType: "Resort"
      },
      { 
        codename: "KA_Mysore_Royal", 
        price: "₹10,000", 
        threat: "Low", 
        vfm: "93%", 
        duration: "2D/1N", 
        brief: "Palace illumination audit.", 
        tacticalBrief: "Wodeyar dynasty HQ. Sandalwood scent prevalent. Sunday illumination critical timing.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Karnataka/KA_Mysore_Royal.png'}], 
        inclusions: ["Heritage Hotel", "Palace Entry"], 
        lockedInclusions: ["Dasara Pass", "Mylari Dosa"],
        intelLevel: 2,
        optimalSeason: "OCT-FEB",
        weather: { temp: "28°C", condition: "Clear", humidity: "40%" },
        transportMode: "Land",
        stayType: "Hotel"
      },
      { 
        codename: "KA_Kabini_Safari", 
        price: "₹18,000", 
        threat: "Medium", 
        vfm: "89%", 
        duration: "3D/2N", 
        brief: "Black panther tracking.", 
        tacticalBrief: "Saya (Black Panther) territory. Boat safari option. High cost, high rarity.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Karnataka/KA_Kabini_Safari.png'}], 
        inclusions: ["River Lodge", "Boat Safari"], 
        lockedInclusions: ["Leopard Spotting", "Coracle Ride"],
        intelLevel: 4,
        optimalSeason: "OCT-JUN",
        weather: { temp: "26°C", condition: "Humid", humidity: "65%" },
        transportMode: "Water",
        stayType: "Resort"
      },
      { 
        codename: "KA_Murudeshwar_Dive", 
        price: "₹14,500", 
        threat: "High", 
        vfm: "92%", 
        duration: "3D/2N", 
        brief: "Netrani Island aquatic ops.", 
        tacticalBrief: "Coral reef scan. Second largest Shiva statue visual reference. Visibility variable.",
        media: [{src:'https://palatepilgrim.com/hubfs/VWW%20Destinations/Karnataka/KA_Murudeshwar_Dive.png'}], 
        inclusions: ["Hotel", "Scuba Dive"], 
        lockedInclusions: ["Shiva Statue Top", "Fish Thali"],
        intelLevel: 3,
        optimalSeason: "OCT-MAY",
        weather: { temp: "31°C", condition: "Sunny", humidity: "80%" },
        transportMode: "Water",
        stayType: "Hotel"
      }
    ]
  }
};

export const ETHOS_DATA: Ethos[] = [
  { id: "01", title: "ASPIRATION ACCESSIBILITY", desc: "Travel is a right. We hack pricing models to keep exploration open source.", icon: "🔓" },
  { id: "02", title: "FOMO INOCULATION", desc: "We filter social noise. Only tactical, high-value experiences make the cut.", icon: "🛡️" },
  { id: "03", title: "ZERO TRAP PROTOCOL", desc: "No tourist traps. No hidden fees. Pure ground operative intelligence.", icon: "👁️" }
];
